name: Events Demo 1
on:
  # Complex trigger event for pull request (with action types) and manual trigger
  pull_request:
    types:
      - opened
      - reopened
  workflow_dispatch:
  # types: [opened, edited, reopened] Alternative syntax
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."
